/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestEmailRouteImport } from './routes/test-email'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as HouseOfRasaRouteImport } from './routes/house-of-rasa'
import { Route as HookahRouteImport } from './routes/hookah'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ComingSoonRouteImport } from './routes/coming-soon'
import { Route as AgeRestrictedRouteImport } from './routes/age-restricted'
import { Route as AccessoriesRouteImport } from './routes/accessories'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as CollectionsTarkibRouteImport } from './routes/collections.tarkib'
import { Route as CollectionsMakhmalRouteImport } from './routes/collections.makhmal'
import { Route as CollectionsMajlisRouteImport } from './routes/collections.majlis'
import { Route as ApiNewsletterRouteImport } from './routes/api/newsletter'

const TestEmailRoute = TestEmailRouteImport.update({
  id: '/test-email',
  path: '/test-email',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseOfRasaRoute = HouseOfRasaRouteImport.update({
  id: '/house-of-rasa',
  path: '/house-of-rasa',
  getParentRoute: () => rootRouteImport,
} as any)
const HookahRoute = HookahRouteImport.update({
  id: '/hookah',
  path: '/hookah',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ComingSoonRoute = ComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const AgeRestrictedRoute = AgeRestrictedRouteImport.update({
  id: '/age-restricted',
  path: '/age-restricted',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoriesRoute = AccessoriesRouteImport.update({
  id: '/accessories',
  path: '/accessories',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsTarkibRoute = CollectionsTarkibRouteImport.update({
  id: '/collections/tarkib',
  path: '/collections/tarkib',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsMakhmalRoute = CollectionsMakhmalRouteImport.update({
  id: '/collections/makhmal',
  path: '/collections/makhmal',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsMajlisRoute = CollectionsMajlisRouteImport.update({
  id: '/collections/majlis',
  path: '/collections/majlis',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsletterRoute = ApiNewsletterRouteImport.update({
  id: '/api/newsletter',
  path: '/api/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRoute
  '/age-restricted': typeof AgeRestrictedRoute
  '/coming-soon': typeof ComingSoonRoute
  '/contact': typeof ContactRoute
  '/hookah': typeof HookahRoute
  '/house-of-rasa': typeof HouseOfRasaRoute
  '/partners': typeof PartnersRoute
  '/test-email': typeof TestEmailRoute
  '/api/newsletter': typeof ApiNewsletterRoute
  '/collections/majlis': typeof CollectionsMajlisRoute
  '/collections/makhmal': typeof CollectionsMakhmalRoute
  '/collections/tarkib': typeof CollectionsTarkibRoute
  '/collections/': typeof CollectionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRoute
  '/age-restricted': typeof AgeRestrictedRoute
  '/coming-soon': typeof ComingSoonRoute
  '/contact': typeof ContactRoute
  '/hookah': typeof HookahRoute
  '/house-of-rasa': typeof HouseOfRasaRoute
  '/partners': typeof PartnersRoute
  '/test-email': typeof TestEmailRoute
  '/api/newsletter': typeof ApiNewsletterRoute
  '/collections/majlis': typeof CollectionsMajlisRoute
  '/collections/makhmal': typeof CollectionsMakhmalRoute
  '/collections/tarkib': typeof CollectionsTarkibRoute
  '/collections': typeof CollectionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRoute
  '/age-restricted': typeof AgeRestrictedRoute
  '/coming-soon': typeof ComingSoonRoute
  '/contact': typeof ContactRoute
  '/hookah': typeof HookahRoute
  '/house-of-rasa': typeof HouseOfRasaRoute
  '/partners': typeof PartnersRoute
  '/test-email': typeof TestEmailRoute
  '/api/newsletter': typeof ApiNewsletterRoute
  '/collections/majlis': typeof CollectionsMajlisRoute
  '/collections/makhmal': typeof CollectionsMakhmalRoute
  '/collections/tarkib': typeof CollectionsTarkibRoute
  '/collections/': typeof CollectionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessories'
    | '/age-restricted'
    | '/coming-soon'
    | '/contact'
    | '/hookah'
    | '/house-of-rasa'
    | '/partners'
    | '/test-email'
    | '/api/newsletter'
    | '/collections/majlis'
    | '/collections/makhmal'
    | '/collections/tarkib'
    | '/collections/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessories'
    | '/age-restricted'
    | '/coming-soon'
    | '/contact'
    | '/hookah'
    | '/house-of-rasa'
    | '/partners'
    | '/test-email'
    | '/api/newsletter'
    | '/collections/majlis'
    | '/collections/makhmal'
    | '/collections/tarkib'
    | '/collections'
  id:
    | '__root__'
    | '/'
    | '/accessories'
    | '/age-restricted'
    | '/coming-soon'
    | '/contact'
    | '/hookah'
    | '/house-of-rasa'
    | '/partners'
    | '/test-email'
    | '/api/newsletter'
    | '/collections/majlis'
    | '/collections/makhmal'
    | '/collections/tarkib'
    | '/collections/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessoriesRoute: typeof AccessoriesRoute
  AgeRestrictedRoute: typeof AgeRestrictedRoute
  ComingSoonRoute: typeof ComingSoonRoute
  ContactRoute: typeof ContactRoute
  HookahRoute: typeof HookahRoute
  HouseOfRasaRoute: typeof HouseOfRasaRoute
  PartnersRoute: typeof PartnersRoute
  TestEmailRoute: typeof TestEmailRoute
  ApiNewsletterRoute: typeof ApiNewsletterRoute
  CollectionsMajlisRoute: typeof CollectionsMajlisRoute
  CollectionsMakhmalRoute: typeof CollectionsMakhmalRoute
  CollectionsTarkibRoute: typeof CollectionsTarkibRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-email': {
      id: '/test-email'
      path: '/test-email'
      fullPath: '/test-email'
      preLoaderRoute: typeof TestEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/house-of-rasa': {
      id: '/house-of-rasa'
      path: '/house-of-rasa'
      fullPath: '/house-of-rasa'
      preLoaderRoute: typeof HouseOfRasaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hookah': {
      id: '/hookah'
      path: '/hookah'
      fullPath: '/hookah'
      preLoaderRoute: typeof HookahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coming-soon': {
      id: '/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof ComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/age-restricted': {
      id: '/age-restricted'
      path: '/age-restricted'
      fullPath: '/age-restricted'
      preLoaderRoute: typeof AgeRestrictedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessories': {
      id: '/accessories'
      path: '/accessories'
      fullPath: '/accessories'
      preLoaderRoute: typeof AccessoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/tarkib': {
      id: '/collections/tarkib'
      path: '/collections/tarkib'
      fullPath: '/collections/tarkib'
      preLoaderRoute: typeof CollectionsTarkibRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/makhmal': {
      id: '/collections/makhmal'
      path: '/collections/makhmal'
      fullPath: '/collections/makhmal'
      preLoaderRoute: typeof CollectionsMakhmalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/majlis': {
      id: '/collections/majlis'
      path: '/collections/majlis'
      fullPath: '/collections/majlis'
      preLoaderRoute: typeof CollectionsMajlisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/newsletter': {
      id: '/api/newsletter'
      path: '/api/newsletter'
      fullPath: '/api/newsletter'
      preLoaderRoute: typeof ApiNewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessoriesRoute: AccessoriesRoute,
  AgeRestrictedRoute: AgeRestrictedRoute,
  ComingSoonRoute: ComingSoonRoute,
  ContactRoute: ContactRoute,
  HookahRoute: HookahRoute,
  HouseOfRasaRoute: HouseOfRasaRoute,
  PartnersRoute: PartnersRoute,
  TestEmailRoute: TestEmailRoute,
  ApiNewsletterRoute: ApiNewsletterRoute,
  CollectionsMajlisRoute: CollectionsMajlisRoute,
  CollectionsMakhmalRoute: CollectionsMakhmalRoute,
  CollectionsTarkibRoute: CollectionsTarkibRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
