/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as HouseOfRasaRouteImport } from './routes/house-of-rasa'
import { Route as HookahsRouteImport } from './routes/hookahs'
import { Route as HookahRouteImport } from './routes/hookah'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AccessoriesRouteImport } from './routes/accessories'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'

const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseOfRasaRoute = HouseOfRasaRouteImport.update({
  id: '/house-of-rasa',
  path: '/house-of-rasa',
  getParentRoute: () => rootRouteImport,
} as any)
const HookahsRoute = HookahsRouteImport.update({
  id: '/hookahs',
  path: '/hookahs',
  getParentRoute: () => rootRouteImport,
} as any)
const HookahRoute = HookahRouteImport.update({
  id: '/hookah',
  path: '/hookah',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoriesRoute = AccessoriesRouteImport.update({
  id: '/accessories',
  path: '/accessories',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRoute
  '/contact': typeof ContactRoute
  '/hookah': typeof HookahRoute
  '/hookahs': typeof HookahsRoute
  '/house-of-rasa': typeof HouseOfRasaRoute
  '/partners': typeof PartnersRoute
  '/collections/': typeof CollectionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRoute
  '/contact': typeof ContactRoute
  '/hookah': typeof HookahRoute
  '/hookahs': typeof HookahsRoute
  '/house-of-rasa': typeof HouseOfRasaRoute
  '/partners': typeof PartnersRoute
  '/collections': typeof CollectionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRoute
  '/contact': typeof ContactRoute
  '/hookah': typeof HookahRoute
  '/hookahs': typeof HookahsRoute
  '/house-of-rasa': typeof HouseOfRasaRoute
  '/partners': typeof PartnersRoute
  '/collections/': typeof CollectionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessories'
    | '/contact'
    | '/hookah'
    | '/hookahs'
    | '/house-of-rasa'
    | '/partners'
    | '/collections/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessories'
    | '/contact'
    | '/hookah'
    | '/hookahs'
    | '/house-of-rasa'
    | '/partners'
    | '/collections'
  id:
    | '__root__'
    | '/'
    | '/accessories'
    | '/contact'
    | '/hookah'
    | '/hookahs'
    | '/house-of-rasa'
    | '/partners'
    | '/collections/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessoriesRoute: typeof AccessoriesRoute
  ContactRoute: typeof ContactRoute
  HookahRoute: typeof HookahRoute
  HookahsRoute: typeof HookahsRoute
  HouseOfRasaRoute: typeof HouseOfRasaRoute
  PartnersRoute: typeof PartnersRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/house-of-rasa': {
      id: '/house-of-rasa'
      path: '/house-of-rasa'
      fullPath: '/house-of-rasa'
      preLoaderRoute: typeof HouseOfRasaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hookahs': {
      id: '/hookahs'
      path: '/hookahs'
      fullPath: '/hookahs'
      preLoaderRoute: typeof HookahsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hookah': {
      id: '/hookah'
      path: '/hookah'
      fullPath: '/hookah'
      preLoaderRoute: typeof HookahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessories': {
      id: '/accessories'
      path: '/accessories'
      fullPath: '/accessories'
      preLoaderRoute: typeof AccessoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessoriesRoute: AccessoriesRoute,
  ContactRoute: ContactRoute,
  HookahRoute: HookahRoute,
  HookahsRoute: HookahsRoute,
  HouseOfRasaRoute: HouseOfRasaRoute,
  PartnersRoute: PartnersRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
